name: Publish Release
on:
  release:
    types: [ created ]
jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build the lib
        run: gradle :remote-robot:build
      - name: Build the plugin
        run: gradle :robot-server-plugin:buildPlugin
      - name: Publish the plugin
        env:
          SPACE_INTERNAL_ACTOR: ${{ secrets.SPACE_INTERNAL_ACTOR }}
          SPACE_INTERNAL_TOKEN: ${{ secrets.SPACE_INTERNAL_TOKEN }}
          RELEASE: 'true'
        run: gradle :robot-server:publishRobotServerPluginPublicationToSpacePublicRepository
      - name: Publish the lib
        env:
          SPACE_INTERNAL_ACTOR: ${{ secrets.SPACE_INTERNAL_ACTOR }}
          SPACE_INTERNAL_TOKEN: ${{ secrets.SPACE_INTERNAL_TOKEN }}
        run: gradle :remote-robot:publishRemoteRobotPublicationToSpacePublicRepository
      - name: Upload the plugin to the relase page
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'robot-server-plugin/build/distributions/robot-server-plugin*.zip'